# Generated by Django 3.1.3 on 2020-11-23 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='name',
            field=models.CharField(help_text='Ingrese el nombre de la Categoria', max_length=200),
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre del Productos', max_length=200)),
                ('especificacion', models.CharField(help_text='Ingrese el nombre de la especificacion', max_length=200)),
                ('imagen', models.CharField(help_text='Ingrese url de la imagen', max_length=200)),
                ('status', models.CharField(blank=True, choices=[('a', 'Agotado'), ('d', 'Disponible')], default='d', help_text='Disponibilidad del Producto', max_length=1)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ventas.categoria')),
            ],
        ),
    ]
