# Generated by Django 3.1.3 on 2020-11-23 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_auto_20201123_0129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
