# Generated by Django 3.1.3 on 2020-11-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0004_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(help_text='Ingrese la contrasena', max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(help_text='Ingrese el correo de usuario', max_length=200),
        ),
    ]
