# Generated by Django 3.1.3 on 2020-11-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0005_auto_20201123_0151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
