# Generated by Django 3.1.3 on 2020-12-03 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0007_auto_20201203_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='kilos',
        ),
    ]
