# Generated by Django 3.1.3 on 2020-12-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0008_auto_20201203_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='kilos',
            field=models.IntegerField(help_text='Ingrese el nombre del Productos', max_length=200),
        ),
    ]
